CREATE TABLE images_table (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    image_data OID NOT NULL,
    image_name TEXT NOT NULL,
    description TEXT,
    upload_date DATE NOT NULL
);

CREATE TABLE tags_table (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tag_name TEXT NOT NULL
);

CREATE TABLE image_tags (
    image_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    CONSTRAINT pk_image_tags PRIMARY KEY (image_id, tag_id),
    CONSTRAINT fk_image_table FOREIGN KEY (image_id) REFERENCES images_table(id),
    CONSTRAINT fk_tags_table FOREIGN KEY (tag_id) REFERENCES tags_table(id)
);

CREATE INDEX image_id_index ON image_tags(image_id);
CREATE INDEX tag_id_index ON image_tags(tag_id);