CREATE TABLE image
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    image_data  OID  NOT NULL,
    thumbnail   OID  NOT NULL,
    name        TEXT NOT NULL CHECK ( LENGTH(name) <= 20 ),
    description TEXT,
    upload_date DATE NOT NULL
);

CREATE TABLE tag
(
    id   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
);

CREATE TABLE image_tags
(
    image_id BIGINT NOT NULL,
    tag_id   BIGINT NOT NULL,
    CONSTRAINT pk_image_tags PRIMARY KEY (image_id, tag_id),
    CONSTRAINT fk_image_table FOREIGN KEY (image_id) REFERENCES image (id),
    CONSTRAINT fk_tags_table FOREIGN KEY (tag_id) REFERENCES tag (id)
);

CREATE INDEX idx_image_tags_image_id ON image_tags (image_id);
CREATE INDEX idx_image_tags_tag_id ON image_tags (tag_id);
CREATE INDEX idx_tag_name ON tag (name);